---
title: "Paper Figures and Text"
format: html
editor: visual
---

## Loading in the Libraries for Everything

```{r}
library(tidyverse)
library(ggplot2)
library(bbmle) #For ICtab
library(car)
library(ggpubr)
library(ggdist)
library(emmeans)
library(lme4)
library(multcompView)
library(pracma)
library(igraph)
library(MASS)
library(rstatix)
library(nlme)
library(glmmTMB)
library(patchwork)
```

## Functions and Variables

```{r}
rad2deg <- function(rad) {(rad * 180) / (pi)}
deg2rad <- function(deg) {(deg * pi) / (180)}
round_any <- function(x, accuracy, f=round){f(x/ accuracy) * accuracy}

deg_ang_mean <- function(x){rad2deg(atan2(mean(sin(deg2rad(x))),mean(cos(deg2rad(x)))))}
rad_ang_mean <- function(x){atan2(mean(sin(x)),mean(cos(x)))}

fold_angle_0_360_to_0_180 <- function(x){abs(abs(x-180)-180)}

fold_angle_neg_180_180_to_neg_90_90 <- function(x){ifelse(x > 90,90-abs(90-x),ifelse(x < -90, -90+abs(-90-x), x))}

min_n <- function(x,n){sort(x)[1:n]}
max_n <- function(x,n){sort(x,decreasing = TRUE)[1:n]}

light_no_ab_color = "#9C9C9C"   #"#C62E65" #A1BAA4" #"#d4d7dd" 06D6A0
light_ab_color = "#f5ba9e"
dark_no_ab_color = "#5e94d4"
dark_ab_color = "#49A078"   #"#1E4371"
sim_color = "#777777"

flow_split_still = "#F59DE2"
flow_split_flow = "#5DD492"

dark_split_light = "#5e94d4"
dark_split_dark = "#011627"

fish_colors = c('Giant Danio'='#666699', 'Cherry Barb'='#e23354', 'Neon Tetra'='#66cc00')

tailbeat_len = 19

allowed_flow_type = c("Still Water","Flowing Water (2 BL/s)")

dot_binwidth = 0.022
neuromast_dot_binwidth = 0.04

text_size = 10
sig_text_size = 6
star_size = 6

# for turning data
x_offset <- 1.95
y_offset <- 1.15
```

```{r}
get_n_groups <- function(HeadX, HeadY, HeadZ, gDist){
  
  HeadX <- na.omit(HeadX)
  HeadY <- na.omit(HeadY)
  HeadZ <- na.omit(HeadZ)
  
  #Need at least 5 fish for this
  if(length(HeadX) < 5){
    return(NA)
  }
  
  A <- matrix(c(HeadX, HeadY, HeadZ), nrow =  length(HeadX), ncol = 3)
  B <- matrix(c(HeadX, HeadY,HeadZ), nrow =  length(HeadX), ncol = 3)
  
  X <- (distmat(A, B) <= max(gDist))
  
  #print(X)
  
  g <- graph_from_adjacency_matrix(X, mode = "lower", weighted = "weight")
  
  return(components(g)$no)
}
```

```{r}

all_fish_comp <- rbind(read.csv("Data/Fish_Comp_Values_3D_Giant Danio.csv"),
                       read.csv("Data/Fish_Comp_Values_3D_Cherry Barb.csv"),
                       read.csv("Data/Fish_Comp_Values_3D_Neon Tetra.csv"))

write.csv(all_fish_comp,"Data/Fish_Comp_Values_3D.csv")

all_fish_comp <- rbind(read.csv("Data/Fish_School_Values_3D_Giant Danio.csv"),
                       read.csv("Data/Fish_School_Values_3D_Cherry Barb.csv"),
                       read.csv("Data/Fish_School_Values_3D_Neon Tetra.csv"))

write.csv(all_fish_comp,"Data/Fish_School_Values_3D.csv")

all_fish_comp <- rbind(read.csv("Data/Fish_Raw_Points_3D_Giant Danio.csv"),
                       read.csv("Data/Fish_Raw_Points_3D_Cherry Barb.csv"),
                       read.csv("Data/Fish_Raw_Points_3D_Neon Tetra.csv"))

write.csv(all_fish_comp,"Data/Fish_Raw_Points_3D.csv")

```

## School Summary Stats

```{r}
school_data <- read.csv("Data/Fish_School_Values_3D.csv")

#school_data <- na.omit(school_data)

school_data <- school_data %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           filter(School_Speed <= 5) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), 
                                  Darkness = factor(Darkness), Species = factor(Species)) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Species = fct_relevel(Species, c("Giant Danio","Cherry Barb","Neon Tetra"))) %>%
                           mutate(Ablation_Species = factor(paste(Ablation,Species,sep="/n"))) %>%
                            
                           # ### Used to remove every third point to reduce autocorrelation
                           mutate(Date = paste(Year,Month,Day,sep="_"),
                                  Date_Trial = paste(Year,Month,Day,Trial,sep="_")) %>%
                           group_by(Date_Trial) %>%
                           #filter(row_number() %% 2 == 1) %>%
                           ungroup() %>%
                           # ###
                          
                           group_by(Ablation_Species) %>%
                           mutate(NND_Mean_Val = mean(NND,na.rm = T), NND_SD_Val = sd(NND,na.rm = T),
                                  Polar_Mean_Val = mean(School_Polar,na.rm = T), Polar_SD_Val = sd(School_Polar,na.rm = T),
                                  Speed_Mean_Val = mean(School_Speed,na.rm = T), Speed_SD_Val = sd(School_Speed,na.rm = T),
                                  Groups_Mean_Val = mean(Groups,na.rm = T), Groups_SD_Val = sd(Groups,na.rm = T),
                                  Mean_Groups_Mean_Val = mean(Mean_Groups,na.rm = T), Mean_Groups_SD_Val = sd(Mean_Groups,na.rm = T)) %>%
                           ungroup()
```

### NND Plot

```{r}
school_data <-
  school_data |> 
  mutate(Ablation = fct_recode(Ablation, Control = "No Ablation"))
```

```{r}

nnd_no_out <- school_data %>% group_by(Ablation,Species) %>%
                              filter(!is.na(NND)) %>%
                              filter(NND >= median(NND, nan.rm=T) - IQR(NND,na.rm =T)*1.5 &
                                     NND <= median(NND, nan.rm=T) + IQR(NND,na.rm =T)*1.5) %>%
                              ungroup()

nnd_label_df <- tibble(Species = unique(nnd_no_out$Species),
                       xstar = c(1.5, 1.5, 1.5),
                       ystar = c(1.2, 2.1, 2.3),
                       p.signif = c(NA,"*","***"))

nnd_still <- ggplot()+
  facet_wrap(~Species)+
  stat_dots(nnd_no_out, mapping = aes(x = Ablation, y = NND, color = Ablation, fill = Ablation),
            side = "both", binwidth = unit(dot_binwidth, "npc"))+
  geom_point(nnd_no_out, mapping = aes(x = Ablation, y = NND_Mean_Val), size = 2, color = "Black", shape=5)+
  geom_errorbar(nnd_no_out, mapping = aes(x = Ablation,ymin=NND_Mean_Val-NND_SD_Val, ymax=NND_Mean_Val+NND_SD_Val),
                width=.4, color = "Black")+
    geom_line(nnd_no_out, mapping = aes(x = Ablation, y = NND_Mean_Val, group = 1), size = 1, color = "Black", linetype = "dashed")+
  geom_text(data = nnd_label_df, aes(x = xstar, y = ystar, label = p.signif), hjust = 'center',
            vjust = 'center', size = star_size)+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color, dark_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color, dark_ab_color)) +
  xlab("") +
  ylab("School NND (BL)") +
  theme_light(base_size = text_size)+ 
  ylim(0,5)+
  theme(legend.position = "none") +
  scale_x_discrete(labels=function(x){sub(",\\s", "\n", x)})

nnd_still
```

### Polarization

```{r}

polar_no_out <- school_data %>% group_by(Ablation,Species) %>%
                              filter(!is.na(School_Polar)) %>%
                              filter(School_Polar >= median(School_Polar, nan.rm=T) - IQR(School_Polar,na.rm =T)*1.5 &
                                     School_Polar <= median(School_Polar, nan.rm=T) + IQR(School_Polar,na.rm =T)*1.5) %>%
                              ungroup()

polar_label_df <- tibble(Species = unique(polar_no_out$Species),
                  Ablation = rep("Control", 3),
                  group1 = rep("Control", 3),
                  group2 = rep("Ablated", 3),
                  p.signif = c("ns","ns","ns"))

polar_still <- ggplot()+
  facet_wrap(~Species)+
  stat_dots(polar_no_out, mapping = aes(x = Ablation, y = School_Polar, color = Ablation, fill = Ablation),
            side = "both", binwidth = unit(dot_binwidth, "npc"))+
  geom_point(polar_no_out, mapping = aes(x = Ablation, y = Polar_Mean_Val), size = 2, color = "Black", shape=5)+
  geom_errorbar(polar_no_out, mapping = aes(x = Ablation,ymin=Polar_Mean_Val-Polar_SD_Val, ymax=Polar_Mean_Val+Polar_SD_Val),
                width=.4, color = "Black")+
  geom_line(polar_no_out, mapping = aes(x = Ablation, y = Polar_Mean_Val, group = 1), size = 1, color = "Black", linetype = "dashed")+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color, dark_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color, dark_ab_color)) +
  xlab("") +
  ylab("Polarization") +
  theme_light(base_size = text_size)+ 
  theme(legend.position = "none") +
  ylim(0,1)+
  scale_x_discrete(labels=function(x){sub(",\\s", "\n", x)})

polar_still
```

### Speed

```{r}

speed_no_out <- school_data %>% group_by(Ablation,Species) %>%
                              filter(!is.na(School_Speed)) %>%
                              filter(School_Speed >= median(School_Speed, nan.rm=T) - IQR(School_Speed,na.rm =T)*1.5 &
                                     School_Speed <= median(School_Speed, nan.rm=T) + IQR(School_Speed,na.rm =T)*1.5) %>%
                              ungroup()

speed_label_df <- tibble(Species = unique(speed_no_out$Species),
                         xstar = c(1.5, 1.5, 1.5),
                         ystar = c(2.1, 3.2, 2.2),
                         p.signif = c("*","****","****"))

speed_still <- ggplot()+
  facet_wrap(~Species)+
  stat_dots(speed_no_out, mapping = aes(x = Ablation, y = School_Speed, color = Ablation, fill = Ablation),
            side = "both", binwidth = unit(dot_binwidth, "npc"))+
  geom_point(speed_no_out, mapping = aes(x = Ablation, y = Speed_Mean_Val), size = 2, color = "Black", shape=5)+
  geom_line(speed_no_out, mapping = aes(x = Ablation, y = Speed_Mean_Val, group = 1), size = 1, color = "Black", linetype = "dashed")+
  geom_errorbar(speed_no_out, mapping = aes(x = Ablation,ymin=Speed_Mean_Val-Speed_SD_Val, ymax=Speed_Mean_Val+Speed_SD_Val),
                width=.4, color = "Black")+
  geom_text(data = speed_label_df, aes(x = xstar, y = ystar, label = p.signif), hjust = 'center',
            vjust = 'center', size = star_size)+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color, dark_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, light_ab_color, dark_no_ab_color, dark_ab_color)) +
  xlab("") +
  ylab("Mean Speed\nof Fish (BL/s)") +
  theme_light(base_size = text_size)+ 
  theme(legend.position = "none") +
  ylim(0,5)+
  scale_x_discrete(labels=function(x){sub(",\\s", "\n", x)})

speed_still
```

### Now we combine them

```{r}
school_stats_mega_plot <- 
  (nnd_still / polar_still / speed_still + plot_annotation(tag_levels = 'A')) &
  theme_minimal(base_size = text_size) &
  theme(panel.grid.minor = element_blank(),
        legend.position = "none")


ggsave("Paper Figures/Figure 2.pdf", school_stats_mega_plot,
       width = 4.7, height = 6, units = 'in')
```

```{r}
school_stats_mega_plot <- ggarrange(nnd_still, 
                                    polar_still,
                                    speed_still,
          labels = c("A", "B", "C", "D"),
          ncol = 1, nrow = 3)  

school_stats_mega_plot

ggsave("Paper Figures/Figure 2.png", school_stats_mega_plot, width = 10, height = 20)
ggsave("Paper Figures/Figure 2.pdf", school_stats_mega_plot, width = 10, height = 20)
```

### Number of Groups

```{r}
all_fish_comp <- read.csv("Data/Fish_Raw_Points_3D.csv") %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Species = fct_relevel(Species, c("Giant Danio","Cherry Barb", "Neon Tetra"))) %>%
                           mutate(Ablation_Species = factor(paste(Ablation,Species,sep="/n")))

# #Uncomment with new data, takes a long time to run just for graph edits
# all_fish_comp_groups <- all_fish_comp %>% expand_grid(Group_Dist = seq(0,15,0.2)) %>%
#                                           group_by(Species, Ablation, Ablation_Species,
#                                                    Year, Month, Day, Trial, Tailbeat, Frame, Group_Dist) %>%
#                                           summarize(n_groups = get_n_groups(Head_X,Head_Y,Head_Z,Group_Dist)) %>%
#                                           ungroup() %>%
#                                           group_by(Species, Ablation, Ablation_Species,
#                                                    Year, Month, Day, Trial, Tailbeat, Group_Dist) %>%
#                                           summarize(Groups = as.integer(mean(n_groups, na.rm = TRUE))) %>%
#                                           ungroup() %>%
# 
#                                            # ### Used to remove every third point to reduce autocorrelation
#                                            #filter(Tailbeat %% 3 == 1) %>%
#                                           na.omit()
# 
# saveRDS(all_fish_comp_groups, "all_fish_comp_groups.RDS")

all_fish_comp_groups <- readRDS("all_fish_comp_groups.RDS")

all_fish_comp_groups <- all_fish_comp_groups %>% filter(!(Species == "Giant Danio" & Group_Dist > 3))

group_sum_data <- all_fish_comp_groups %>% filter(Groups > 0) %>% group_by(Ablation, Species, Groups, Group_Dist) %>%
                            summarise(count = n()) %>%
                            ungroup() %>%
                            mutate(Groups = as.factor(Groups),
                                   Groups = fct_rev(Groups))

group_sum_data_1 <- group_sum_data %>% complete(Species,Ablation,Group_Dist,Groups,fill=list(count=0)) %>%
                                       group_by(Species,Ablation,Group_Dist) %>%
                                       mutate(total = sum(count),
                                              Percent_Group = count / total) %>%
                                       ungroup() %>%
                                       filter(Groups == 1)

group_sum_data_1 <- group_sum_data_1 %>% filter(!(Species == "Giant Danio" & Group_Dist > 3))

group_sum_data_1_binom <- all_fish_comp_groups %>% mutate(Is_One = ifelse(Groups == 1, 1, 0))

#group_1_glm <- glm(Is_One ~ Ablation*Species*Group_Dist, data = group_sum_data_1_binom, family = "binomial")
group_1_glm <- glmmTMB(Is_One ~ Ablation*Species*Group_Dist + ar1(as.factor(Tailbeat) + 0|Trial:Species), 
                             data = group_sum_data_1_binom, family = "binomial")
group_1_aov <- Anova(group_1_glm, type=c("III"))
group_1_aov

group_sum_data_1_trimmed <- group_sum_data_1 %>% filter(Species == "Giant Danio" | 
                                                          (Species != "Giant Danio" & Group_Dist %% 1 == 0))%>%
                                                          filter(Species != "Giant Danio" | 
                                                          (Species == "Giant Danio" & Group_Dist <= 5))

group_sum_data_1_binom_pred <- group_sum_data_1_binom %>% mutate(predVals = predict(group_1_glm, type="response")) %>%
                                                          group_by(Ablation,Species,Group_Dist) %>%
                                                          summarise(meanPredVals = mean(predVals)) %>%
                                                          ungroup() %>% 
                                                          filter(Species == "Giant Danio" | 
                                                          (Species != "Giant Danio" & Group_Dist %% 1 == 0)) %>%
                                                          filter(Species != "Giant Danio" | 
                                                          (Species == "Giant Danio" & Group_Dist <= 5))
```


```{r}
group_still <- ggplot(group_sum_data_1_trimmed, aes(Group_Dist, Percent_Group, color = Ablation))+
  facet_wrap(~Species, scales = "free")+
  geom_point()+
  geom_line(data = group_sum_data_1_binom_pred, aes(x = Group_Dist, y = meanPredVals), size = 1) + 
  scale_color_manual(values = c(light_no_ab_color,light_ab_color,dark_no_ab_color,dark_ab_color)) +
  theme(legend.position = "none")+
  xlab("Maximum Distance to Connect Group (BL)")+
  ylab("Proportion of Time in 1 Group")+
  scale_y_continuous(breaks = seq(0,1,0.25), limits = c(0,1))+
  theme_minimal(base_size = text_size)+
  theme(legend.position = "none")

group_still
```


```{r}
ggsave("Paper Figures/Subgroup_Graphs.pdf", group_still, 
       width = 4.5, height = 2, units = "in")

```

### Neuromast density

```{r}

neuromast_counts <- read.csv("Data/neuromast_counts.csv") %>%
                    dplyr::select(-c(x,y,survey.id)) %>%
                    separate(image, c("Fish","ID"), sep = "_") %>%
                    mutate(Fish = case_when(Fish == "GD" ~ "Giant Danio",
                                            Fish == "CB" ~ "Cherry Barb",
                                            Fish == "NT" ~ "Neon Tetra")) %>%
                    mutate(Fish = fct_relevel(Fish, c("Giant Danio","Cherry Barb", "Neon Tetra"))) %>%
                    mutate(ID = gsub(".jpg", "", ID),
                           All.Superficial = Superficial.Above.LL+Superficial.Below.LL+Superficial.Head+
                                             Superficial.LL.Scales+Superficial.Operculum+Superficial.Tailfin,
                           All.Superficial.Area = All.Superficial/Area,
                           Head.Canal.Neuromast.Length = Canal.Head/Length,
                           Canal.Neuromast.Length = (Canal.Neuromast-Canal.Head)/Length,
                           Head.Superficial.Area = (Superficial.Head+Superficial.Operculum)/Area,
                           Body.Superficial.Area = (Superficial.Above.LL+Superficial.Below.LL+
                                                      Superficial.LL.Scales++Superficial.Tailfin)/Area)
    
```

```{r}

neuromast_per_area <- neuromast_counts %>% group_by(Fish) %>%
                                          summarise(All.Superficial.Area = All.Superficial.Area,
                                                    All.Superficial.Area.Mean = mean(All.Superficial.Area),
                                                    All.Superficial.Area.SD = sd(All.Superficial.Area),
                                                    Head.Canal.Neuromast.Length = Head.Canal.Neuromast.Length,
                                                    Head.Canal.Neuromast.Length.Mean = mean(Head.Canal.Neuromast.Length),
                                                    Head.Canal.Neuromast.Length.SD = sd(Head.Canal.Neuromast.Length),
                                                    Canal.Neuromast.Length = Canal.Neuromast.Length,
                                                    Canal.Neuromast.Length.Mean = mean(Canal.Neuromast.Length),
                                                    Canal.Neuromast.Length.SD = sd(Canal.Neuromast.Length),
                                                    Head.Superficial.Area = Head.Superficial.Area,
                                                    Head.Superficial.Area.Mean = mean(Head.Superficial.Area),
                                                    Head.Superficial.Area.SD = sd(Head.Superficial.Area),
                                                    Body.Superficial.Area = Body.Superficial.Area,
                                                    Body.Superficial.Area.Mean = mean(Body.Superficial.Area),
                                                    Body.Superficial.Area.SD = sd(Body.Superficial.Area))

my_comparisons = list(c("Cherry Barb", "Giant Danio"),c("Cherry Barb", "Neon Tetra"),c("Giant Danio", "Neon Tetra"))

# total_super <- ggplot(neuromast_per_area, aes(x = Fish, y = All.Superficial.Area, color = Fish, fill = Fish))+
#   stat_dots(side = "both", binwidth = unit(dot_binwidth, "npc")) +
#   geom_point(aes(y = All.Superficial.Area.Mean), color = "black")+
#   geom_errorbar(aes(ymin=All.Superficial.Area.Mean-All.Superficial.Area.SD,
#                     ymax=All.Superficial.Area.Mean+All.Superficial.Area.SD), width=.2, color = "black")+
#   ylab("Superficial Neuromasts per cm^2")+
#   theme_classic()+
#   xlab("")+
#   ylim(0,2000)+
#   stat_compare_means(comparisons = my_comparisons, method = "t.test", label.y = c(1500,1700,1900),
#                      label = "p.signif", hide.ns = TRUE, bracket.size = 0.75, size = 7) +
#   theme(legend.position = "none") +
#   theme(axis.text.x = element_text(size = text_size),
#         axis.text.y = element_text(size = text_size),
#         axis.title.x = element_text(size = text_size),
#         axis.title.y = element_text(size = text_size),
#         strip.text.x = element_text(size = text_size))

```

```{r}
head_canal <- ggplot(neuromast_per_area, aes(x = Fish, y = Head.Canal.Neuromast.Length, color = Fish, fill = Fish))+
  stat_dots(side = "both", binwidth = unit(neuromast_dot_binwidth, "npc")) +
  geom_point(aes(y = Head.Canal.Neuromast.Length.Mean), color = "black", shape=4, size=2)+
  geom_errorbar(aes(ymin=Head.Canal.Neuromast.Length.Mean-Head.Canal.Neuromast.Length.SD,
                    ymax=Head.Canal.Neuromast.Length.Mean+Head.Canal.Neuromast.Length.SD), width=.4, color = "black")+
  ylab("Canal Neuromasts\n(per cm)")+
  scale_color_manual(values = fish_colors) +
  scale_fill_manual(values = fish_colors) +
  scale_x_discrete(labels = c('Giant Danio'='Giant\ndanio',
                              'Neon Tetra'='Neon\ntetra',
                              'Cherry Barb'='Cherry\nbarb')) +
  theme_minimal(base_size = text_size)+
  xlab("")+
  ggtitle('Head') +
  ylim(0,8)+
  stat_compare_means(comparisons = list(c("Cherry Barb", "Neon Tetra")), method = "t.test", label.y = c(7.5),
                     label = "p.signif", hide.ns = TRUE, bracket.size = 0.75, size = 5,
                     tip.length = 0) +
  theme(legend.position = "none",
        panel.grid.minor = element_blank())

head_canal
```


```{r}
body_canal <- ggplot(neuromast_per_area, aes(x = Fish, y = Canal.Neuromast.Length, color = Fish, fill = Fish))+
  stat_dots(side = "both", binwidth = unit(neuromast_dot_binwidth, "npc")) +
  geom_point(aes(y = Canal.Neuromast.Length.Mean), color = "black", shape=4, size=2)+
  geom_errorbar(aes(ymin=Canal.Neuromast.Length.Mean-Canal.Neuromast.Length.SD,
                    ymax=Canal.Neuromast.Length.Mean+Canal.Neuromast.Length.SD), width=.4, color = "black")+
  ylab("") + #Canal Neuromasts\n(per cm)")+
  scale_color_manual(values = fish_colors) +
  scale_fill_manual(values = fish_colors) +
  scale_x_discrete(labels = c('Giant Danio'='Giant\ndanio',
                              'Neon Tetra'='Neon\ntetra',
                              'Cherry Barb'='Cherry\nbarb')) +
  theme_minimal(base_size = text_size)+
  xlab("")+
  ggtitle('Trunk') +
  ylim(0,8)+
  theme(legend.position = "none",
        panel.grid.minor = element_blank()) +
  stat_compare_means(comparisons = list(c("Giant Danio", "Neon Tetra"),
                                        c("Cherry Barb", "Neon Tetra")), bracket.size = 0.75, size = 5,
                     method = "t.test", label = "p.signif", hide.ns = TRUE, label.y = c(7.5,7),
                     tip.length = 0)

body_canal
```


```{r}
head_super <- ggplot(neuromast_per_area, aes(x = Fish, y = Head.Superficial.Area, color = Fish, fill = Fish))+
  stat_dots(side = "both", binwidth = unit(neuromast_dot_binwidth, "npc")) +
  geom_point(aes(y = Head.Superficial.Area.Mean), color = "black", shape=4, size=2)+
  geom_errorbar(aes(ymin=Head.Superficial.Area.Mean-Head.Superficial.Area.SD,
                    ymax=Head.Superficial.Area.Mean+Head.Superficial.Area.SD), width=.4, color = "black")+
  ylab("Superficial Neuromasts\n(per cm^2)")+
  theme_minimal(base_size = text_size)+
  scale_color_manual(values = fish_colors) +
  scale_fill_manual(values = fish_colors) +
  scale_x_discrete(labels = c('Giant Danio'='Giant\ndanio',
                              'Neon Tetra'='Neon\ntetra',
                              'Cherry Barb'='Cherry\nbarb')) +
  xlab("")+
  ylim(0,1060)+
  theme(legend.position = "none",
        panel.grid.minor = element_blank()) +
  stat_compare_means(comparisons = my_comparisons, bracket.size = 0.75, size = 5, label.y = c(250,430,500),
                     method = "t.test", label = "p.signif", hide.ns = TRUE,
                     tip.length = 0)

head_super
```


```{r}
body_super <- ggplot(neuromast_per_area, aes(x = Fish, y = Body.Superficial.Area, color = Fish, fill = Fish))+
  stat_dots(side = "both", binwidth = unit(neuromast_dot_binwidth, "npc")) +
  geom_point(aes(y = Body.Superficial.Area.Mean), color = "black", shape=4, size=2)+
  geom_errorbar(aes(ymin=Body.Superficial.Area.Mean-Body.Superficial.Area.SD,
                    ymax=Body.Superficial.Area.Mean+Body.Superficial.Area.SD), width=.4, color = "black")+
  ylab("") + #Superficial Neuromasts\n(per cm^2)")+
  scale_color_manual(values = fish_colors) +
  scale_fill_manual(values = fish_colors) +
  scale_x_discrete(labels = c('Giant Danio'='Giant\ndanio',
                              'Neon Tetra'='Neon\ntetra',
                              'Cherry Barb'='Cherry\nbarb')) +
  theme_minimal(base_size = text_size)+
  xlab("")+
  ylim(0,1060)+
  theme(legend.position = "none",
        panel.grid.minor = element_blank()) +
  stat_compare_means(comparisons = my_comparisons, bracket.size = 0.75, size = 5
                     , method = "t.test", label = "p.signif", hide.ns = TRUE,
                     label.y = c(400, 800, 900),
                     tip.length = 0)

body_super
```

```{r}
neuromast_mega_plot <- 
  (head_canal + body_canal + head_super + body_super) +
  plot_annotation(tag_levels = 'A')

ggsave("Paper Figures/neuromast_figures.pdf", neuromast_mega_plot, width = 4.2, height = 4)
neuromast_mega_plot
```

```{r}
neuromast_mega_plot <- ggarrange(head_canal,
                                    body_canal,
                                    head_super,
                                    body_super,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)  

neuromast_mega_plot

ggsave("Paper Figures/neuromast_figures.png", neuromast_mega_plot, width = 10, height = 10)
ggsave("Paper Figures/neuromast_figures.pdf", neuromast_mega_plot, width = 10, height = 10)

```
